### ISSUE TITLE
Is it possible to make `yes-or-no` pop up?

### ISSUE THREAD

**Issue by abcdw** [muffinmad/emacs-mini-frame#46]
I figured it out how to make it work for eval-expression (by removing it from ignored commands), but not succeed with `yes-or-no` yet.  Want it to be in a child frame too.

A really cool package, thank you very much for creating it)

**Comment by muffinmad** [comment]
Somehow mini-frame advice is not working when `yes-or-no-p` function is calling `read-from-minibuffer`. Adding `yes-or-no-p` function to the `mini-frame-advice-functions` list will help.

Take a look at `use-short-answers` variable. It allows to use `y-or-n-p` function instead of `yes-or-no-p`. And `y-or-n-p` is working with mini-frame OOTB :)

**Comment by abcdw** [comment]
Andrii Kolomoiets ***@***.***> writes:

> Somehow mini-frame advice is not working when `yes-or-no-p` function
> is calling `read-from-minibuffer`.

Probably because `yes-or-no-p` is not using `read-from-minibuffer`
internally, it seems it's a builtin C function, not elisp.

> Adding `yes-or-no-p` function to the `mini-frame-advice-functions`
> list will help.

It works, thank you for the tip!)

> Take a look at `use-short-answers` variable. It allows to use
> `y-or-n-p` function instead of `yes-or-no-p`. And `y-or-n-p` is
> working with mini-frame OOTB :)

Yep, it's another option, but I'll stick with the first one and will
keep `yes-or-no-p` and `y-or-n-p` separate.
